server.port=${PORT:10000}
server.address=0.0.0.0

spring.datasource.url=jdbc:h2:mem:frete_db
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

frete.taxa.fixa=10.00
frete.moeda=R$
frete.preco.minimo=0.01
frete.preco.maximo=1000000.00
frete.nome.sistema=ALGORITMO CALCULO_FRETE
frete.versao=1.0.0

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
