server.port=${PORT:8080}

spring.datasource.url=jdbc:h2:mem:frete_db
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

frete.taxa.fixa=10.00

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
